# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: capability.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import gobgp_pb2 as gobgp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61pability.proto\x12\x08gobgpapi\x1a\x0bgobgp.proto\";\n\x17MultiProtocolCapability\x12 \n\x06\x66\x61mily\x18\x01 \x01(\x0b\x32\x10.gobgpapi.Family\"\x18\n\x16RouteRefreshCapability\"\x1d\n\x1b\x43\x61rryingLabelInfoCapability\"q\n\x1e\x45xtendedNexthopCapabilityTuple\x12%\n\x0bnlri_family\x18\x01 \x01(\x0b\x32\x10.gobgpapi.Family\x12(\n\x0enexthop_family\x18\x02 \x01(\x0b\x32\x10.gobgpapi.Family\"U\n\x19\x45xtendedNexthopCapability\x12\x38\n\x06tuples\x18\x01 \x03(\x0b\x32(.gobgpapi.ExtendedNexthopCapabilityTuple\"Q\n\x1eGracefulRestartCapabilityTuple\x12 \n\x06\x66\x61mily\x18\x01 \x01(\x0b\x32\x10.gobgpapi.Family\x12\r\n\x05\x66lags\x18\x02 \x01(\r\"r\n\x19GracefulRestartCapability\x12\r\n\x05\x66lags\x18\x01 \x01(\r\x12\x0c\n\x04time\x18\x02 \x01(\r\x12\x38\n\x06tuples\x18\x03 \x03(\x0b\x32(.gobgpapi.GracefulRestartCapabilityTuple\")\n\x1b\x46ourOctetASNumberCapability\x12\n\n\x02\x61s\x18\x01 \x01(\r\"_\n\x16\x41\x64\x64PathCapabilityTuple\x12 \n\x06\x66\x61mily\x18\x01 \x01(\x0b\x32\x10.gobgpapi.Family\x12#\n\x04mode\x18\x02 \x01(\x0e\x32\x15.gobgpapi.AddPathMode\"E\n\x11\x41\x64\x64PathCapability\x12\x30\n\x06tuples\x18\x01 \x03(\x0b\x32 .gobgpapi.AddPathCapabilityTuple\" \n\x1e\x45nhancedRouteRefreshCapability\"h\n\'LongLivedGracefulRestartCapabilityTuple\x12 \n\x06\x66\x61mily\x18\x01 \x01(\x0b\x32\x10.gobgpapi.Family\x12\r\n\x05\x66lags\x18\x02 \x01(\r\x12\x0c\n\x04time\x18\x03 \x01(\r\"g\n\"LongLivedGracefulRestartCapability\x12\x41\n\x06tuples\x18\x01 \x03(\x0b\x32\x31.gobgpapi.LongLivedGracefulRestartCapabilityTuple\"\x1d\n\x1bRouteRefreshCiscoCapability\"0\n\x11UnknownCapability\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x0c*L\n\x0b\x41\x64\x64PathMode\x12\r\n\tMODE_NONE\x10\x00\x12\x10\n\x0cMODE_RECEIVE\x10\x01\x12\r\n\tMODE_SEND\x10\x02\x12\r\n\tMODE_BOTH\x10\x03\x62\x06proto3')

_ADDPATHMODE = DESCRIPTOR.enum_types_by_name['AddPathMode']
AddPathMode = enum_type_wrapper.EnumTypeWrapper(_ADDPATHMODE)
MODE_NONE = 0
MODE_RECEIVE = 1
MODE_SEND = 2
MODE_BOTH = 3


_MULTIPROTOCOLCAPABILITY = DESCRIPTOR.message_types_by_name['MultiProtocolCapability']
_ROUTEREFRESHCAPABILITY = DESCRIPTOR.message_types_by_name['RouteRefreshCapability']
_CARRYINGLABELINFOCAPABILITY = DESCRIPTOR.message_types_by_name['CarryingLabelInfoCapability']
_EXTENDEDNEXTHOPCAPABILITYTUPLE = DESCRIPTOR.message_types_by_name['ExtendedNexthopCapabilityTuple']
_EXTENDEDNEXTHOPCAPABILITY = DESCRIPTOR.message_types_by_name['ExtendedNexthopCapability']
_GRACEFULRESTARTCAPABILITYTUPLE = DESCRIPTOR.message_types_by_name['GracefulRestartCapabilityTuple']
_GRACEFULRESTARTCAPABILITY = DESCRIPTOR.message_types_by_name['GracefulRestartCapability']
_FOUROCTETASNUMBERCAPABILITY = DESCRIPTOR.message_types_by_name['FourOctetASNumberCapability']
_ADDPATHCAPABILITYTUPLE = DESCRIPTOR.message_types_by_name['AddPathCapabilityTuple']
_ADDPATHCAPABILITY = DESCRIPTOR.message_types_by_name['AddPathCapability']
_ENHANCEDROUTEREFRESHCAPABILITY = DESCRIPTOR.message_types_by_name['EnhancedRouteRefreshCapability']
_LONGLIVEDGRACEFULRESTARTCAPABILITYTUPLE = DESCRIPTOR.message_types_by_name['LongLivedGracefulRestartCapabilityTuple']
_LONGLIVEDGRACEFULRESTARTCAPABILITY = DESCRIPTOR.message_types_by_name['LongLivedGracefulRestartCapability']
_ROUTEREFRESHCISCOCAPABILITY = DESCRIPTOR.message_types_by_name['RouteRefreshCiscoCapability']
_UNKNOWNCAPABILITY = DESCRIPTOR.message_types_by_name['UnknownCapability']
MultiProtocolCapability = _reflection.GeneratedProtocolMessageType('MultiProtocolCapability', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPROTOCOLCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.MultiProtocolCapability)
  })
_sym_db.RegisterMessage(MultiProtocolCapability)

RouteRefreshCapability = _reflection.GeneratedProtocolMessageType('RouteRefreshCapability', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEREFRESHCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.RouteRefreshCapability)
  })
_sym_db.RegisterMessage(RouteRefreshCapability)

CarryingLabelInfoCapability = _reflection.GeneratedProtocolMessageType('CarryingLabelInfoCapability', (_message.Message,), {
  'DESCRIPTOR' : _CARRYINGLABELINFOCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.CarryingLabelInfoCapability)
  })
_sym_db.RegisterMessage(CarryingLabelInfoCapability)

ExtendedNexthopCapabilityTuple = _reflection.GeneratedProtocolMessageType('ExtendedNexthopCapabilityTuple', (_message.Message,), {
  'DESCRIPTOR' : _EXTENDEDNEXTHOPCAPABILITYTUPLE,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.ExtendedNexthopCapabilityTuple)
  })
_sym_db.RegisterMessage(ExtendedNexthopCapabilityTuple)

ExtendedNexthopCapability = _reflection.GeneratedProtocolMessageType('ExtendedNexthopCapability', (_message.Message,), {
  'DESCRIPTOR' : _EXTENDEDNEXTHOPCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.ExtendedNexthopCapability)
  })
_sym_db.RegisterMessage(ExtendedNexthopCapability)

GracefulRestartCapabilityTuple = _reflection.GeneratedProtocolMessageType('GracefulRestartCapabilityTuple', (_message.Message,), {
  'DESCRIPTOR' : _GRACEFULRESTARTCAPABILITYTUPLE,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.GracefulRestartCapabilityTuple)
  })
_sym_db.RegisterMessage(GracefulRestartCapabilityTuple)

GracefulRestartCapability = _reflection.GeneratedProtocolMessageType('GracefulRestartCapability', (_message.Message,), {
  'DESCRIPTOR' : _GRACEFULRESTARTCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.GracefulRestartCapability)
  })
_sym_db.RegisterMessage(GracefulRestartCapability)

FourOctetASNumberCapability = _reflection.GeneratedProtocolMessageType('FourOctetASNumberCapability', (_message.Message,), {
  'DESCRIPTOR' : _FOUROCTETASNUMBERCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.FourOctetASNumberCapability)
  })
_sym_db.RegisterMessage(FourOctetASNumberCapability)

AddPathCapabilityTuple = _reflection.GeneratedProtocolMessageType('AddPathCapabilityTuple', (_message.Message,), {
  'DESCRIPTOR' : _ADDPATHCAPABILITYTUPLE,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.AddPathCapabilityTuple)
  })
_sym_db.RegisterMessage(AddPathCapabilityTuple)

AddPathCapability = _reflection.GeneratedProtocolMessageType('AddPathCapability', (_message.Message,), {
  'DESCRIPTOR' : _ADDPATHCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.AddPathCapability)
  })
_sym_db.RegisterMessage(AddPathCapability)

EnhancedRouteRefreshCapability = _reflection.GeneratedProtocolMessageType('EnhancedRouteRefreshCapability', (_message.Message,), {
  'DESCRIPTOR' : _ENHANCEDROUTEREFRESHCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.EnhancedRouteRefreshCapability)
  })
_sym_db.RegisterMessage(EnhancedRouteRefreshCapability)

LongLivedGracefulRestartCapabilityTuple = _reflection.GeneratedProtocolMessageType('LongLivedGracefulRestartCapabilityTuple', (_message.Message,), {
  'DESCRIPTOR' : _LONGLIVEDGRACEFULRESTARTCAPABILITYTUPLE,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.LongLivedGracefulRestartCapabilityTuple)
  })
_sym_db.RegisterMessage(LongLivedGracefulRestartCapabilityTuple)

LongLivedGracefulRestartCapability = _reflection.GeneratedProtocolMessageType('LongLivedGracefulRestartCapability', (_message.Message,), {
  'DESCRIPTOR' : _LONGLIVEDGRACEFULRESTARTCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.LongLivedGracefulRestartCapability)
  })
_sym_db.RegisterMessage(LongLivedGracefulRestartCapability)

RouteRefreshCiscoCapability = _reflection.GeneratedProtocolMessageType('RouteRefreshCiscoCapability', (_message.Message,), {
  'DESCRIPTOR' : _ROUTEREFRESHCISCOCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.RouteRefreshCiscoCapability)
  })
_sym_db.RegisterMessage(RouteRefreshCiscoCapability)

UnknownCapability = _reflection.GeneratedProtocolMessageType('UnknownCapability', (_message.Message,), {
  'DESCRIPTOR' : _UNKNOWNCAPABILITY,
  '__module__' : 'capability_pb2'
  # @@protoc_insertion_point(class_scope:gobgpapi.UnknownCapability)
  })
_sym_db.RegisterMessage(UnknownCapability)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDPATHMODE._serialized_start=1099
  _ADDPATHMODE._serialized_end=1175
  _MULTIPROTOCOLCAPABILITY._serialized_start=43
  _MULTIPROTOCOLCAPABILITY._serialized_end=102
  _ROUTEREFRESHCAPABILITY._serialized_start=104
  _ROUTEREFRESHCAPABILITY._serialized_end=128
  _CARRYINGLABELINFOCAPABILITY._serialized_start=130
  _CARRYINGLABELINFOCAPABILITY._serialized_end=159
  _EXTENDEDNEXTHOPCAPABILITYTUPLE._serialized_start=161
  _EXTENDEDNEXTHOPCAPABILITYTUPLE._serialized_end=274
  _EXTENDEDNEXTHOPCAPABILITY._serialized_start=276
  _EXTENDEDNEXTHOPCAPABILITY._serialized_end=361
  _GRACEFULRESTARTCAPABILITYTUPLE._serialized_start=363
  _GRACEFULRESTARTCAPABILITYTUPLE._serialized_end=444
  _GRACEFULRESTARTCAPABILITY._serialized_start=446
  _GRACEFULRESTARTCAPABILITY._serialized_end=560
  _FOUROCTETASNUMBERCAPABILITY._serialized_start=562
  _FOUROCTETASNUMBERCAPABILITY._serialized_end=603
  _ADDPATHCAPABILITYTUPLE._serialized_start=605
  _ADDPATHCAPABILITYTUPLE._serialized_end=700
  _ADDPATHCAPABILITY._serialized_start=702
  _ADDPATHCAPABILITY._serialized_end=771
  _ENHANCEDROUTEREFRESHCAPABILITY._serialized_start=773
  _ENHANCEDROUTEREFRESHCAPABILITY._serialized_end=805
  _LONGLIVEDGRACEFULRESTARTCAPABILITYTUPLE._serialized_start=807
  _LONGLIVEDGRACEFULRESTARTCAPABILITYTUPLE._serialized_end=911
  _LONGLIVEDGRACEFULRESTARTCAPABILITY._serialized_start=913
  _LONGLIVEDGRACEFULRESTARTCAPABILITY._serialized_end=1016
  _ROUTEREFRESHCISCOCAPABILITY._serialized_start=1018
  _ROUTEREFRESHCISCOCAPABILITY._serialized_end=1047
  _UNKNOWNCAPABILITY._serialized_start=1049
  _UNKNOWNCAPABILITY._serialized_end=1097
# @@protoc_insertion_point(module_scope)
