version: '3'

services:
  db:
    image: mongo
    hostname: mongo
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: sdbgp_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8001:8001"
  gobgp:
    image: jauderho/gobgp:v2.34.0
    hostname: gobgp
    volumes:
      - ./gobgp:/config
    ports:
      - "179:179"
