version: '3'

services:
  db:
    image: mongo
    hostname: mongo
  app:
    build:
      context: ./
      dockerfile: Dockerfile.back
    container_name: sdbgp_app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8001:8001"
  gobgp:
    image: jauderho/gobgp:v2.34.0
    hostname: gobgp
    volumes:
      - ./gobgp_config:/config
    ports:
      - "179:179"
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.front
      args:
        - REACT_APP_API_BASE_PATH=${REACT_APP_API_BASE_PATH}
    env_file:
      - .env
    depends_on:
      - app
    ports:
      - "8888:80"